version: "3.5"
services:
  database:
    build: 
      dockerfile: postgres.Dockerfile
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - rt-office
    volumes:
      - rt-office-db:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak:9.0.2
    ports:
      - 5003:8080
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=password
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=password
    depends_on:
      - database
    networks:
      - rt-office
  nextcloud:
    build: 
      dockerfile: nextcloud.Dockerfile
      context: .
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=database
    volumes:
      - rt-office-nextcloud:/var/www/html
    ports:
      - 5002:80
    networks:
      - rt-office
    depends_on:
      - database
      - keycloak
networks:
  # Network has to be created externally prior to building the app.
  # > docker network create rt-office
  rt-office:
volumes:
  # Create ext. volumes by:
  # > docker volume create rt-office-db
  # > docker volume create rt-office-nextcloud
  rt-office-db:
    external: true
  rt-office-nextcloud:
    external: true